version: '3.8'
services:
  web:
    build: training-diary-backend
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
  react:
    build: training-diary-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DEV_API_HOST=http://localhost:5000
    volumes:
      - ./training-diary-frontend/src:/usr/src/app/src
      - ./training-diary-frontend/public:/usr/src/app/public
volumes:
  mongo-data:
  mongo-configdb:
